version: '2.0'
services:

  unfetter-discover-openssl:
    image: svagi/openssl:latest
    container_name: unfetter-discover-openssl
    entrypoint:
     - openssl
     - req
     - -subj
     - /CN=localhost/DC=localhost/DC=localdomain
     - -new
     - -newkey
     - rsa:2048
     - -days
     - "365"
     - -nodes
     - -x509
     - -keyout
     - /tmp/certs/server.key
     - -out
     - /tmp/certs/server.crt
    volumes:
     - ./certs/:/tmp/certs
  unfetter-ctf-ingest:
    build: unfetter-ctf-ingest
    container_name: unfetter-ctf-ingest
    image: unfetter-ctf-ingest
    volumes:
     - ./unfetter-ctf-ingest/test-data:/tmp/test-data
    environment:
      - API_PROTOCOL=https
      - API_HOST=apihost
      - API_PORT=3000
      - API_CONTEXT=/
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    ports:
    - "3001:10010"
    entrypoint:
     - npm
     - start
    depends_on:
     - cti-stix-store-repository
     - unfetter-discover-api
    links:
     - cti-stix-store-repository:repository
     - unfetter-discover-api:apihost

  unfetter-socket-server:
    build: unfetter-socket-server
    container_name: unfetter-socket-server
    image: unfetter-socket-server
    volumes:
      - .unfetter-socket-server/src:/usr/share/unfetter-socket-server/src
      - ./certs/:/etc/pki/tls/certs
    environment:
      - MONGO_REPOSITORY=repository
      - MONGO_PORT=27017
      - MONGO_DBNAME=stix
    ports:
    - "13333:3333"
    entrypoint:
     - npm
     - run
     - serve
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository

  cti-stix-store-repository:
    image: mongo:3.4.1
    container_name: cti-stix-store-repository
    ports:
    - "27018:27017"
    volumes:
    - ./data/db:/data/db

  unfetter-discover-processor:
    build: unfetter-discover-processor
    container_name: unfetter-discover-processor
    image: unfetter-discover-processor
    volumes:
     - ./travis-sample-data/examples:/tmp/examples
     - ./unfetter-discover-processor/processor.js:/usr/src/app/processor.js
    environment:
     - MONGO_HOST=repository
     - HTTPS_PROXY_URL=
    entrypoint:
     - node
     - processor.js
     - --stix
     - /tmp/examples/unfetter-stix/stix-lite.json
    depends_on:
     - cti-stix-store-repository
    links:
     - cti-stix-store-repository:repository

  unfetter-discover-api:
    build: unfetter-discover-api
    container_name: unfetter-discover-api
    image: unfetter-discover-api
    depends_on:
    - unfetter-discover-openssl
    - cti-stix-store-repository
    - unfetter-socket-server
    links:
    - cti-stix-store-repository:repository
    - unfetter-socket-server:socketserver
    ports:
    - "49360:3000"
    - "5555:5555"
    volumes:
    - ./certs/:/etc/pki/tls/certs
    - ./unfetter-discover-api/test:/usr/share/unfetter-discover-api/test
    - ./unfetter-discover-api/api:/usr/share/unfetter-discover-api/api
    - ./unfetter-discover-api/app.js:/usr/share/unfetter-discover-api/app.js
    environment:
    - CTF_PARSE_HOST=http://unfetter-ctf-ingest
    - PATTERN_HANDLER_DOMAIN = unfetter-pattern-handler
    - PATTERN_HANDLER_PORT = 5000
    - SOCKET_SERVER_DOMAIN = socketserver
    - SOCKET_SERVER_PORT = 3333
    - STIX_API_PROTOCOL=http
    - STIX_API_HOST=cti-stix-store
    - STIX_API_PORT=3000
    - STIX_API_PATH=cti-stix-store-api
    - MONGO_REPOSITORY=repository
    - MONGO_PORT=27017
    - MONGO_DBNAME=stix
    - ENV=dev
    # Options: UAC, TEST, DEMO
    - RUN_MODE=UAC
    # If deployed in a proxy, add the proxy's URL here
    - HTTPS_PROXY_URL=
    entrypoint:
    - npm
    - run
    - debugdev

  