language: node_js
node_js:
  - "9.2"
before_install:
 - npm --loglevel error install -g multi-file-swagger && npm --loglevel error install -g pm2 && npm --loglevel error install -g json2yaml && npm --loglevel error install -g swagger && apk add --update curl

# Install Dependencies
 - npm --loglevel error install && \
    # The NPM package depends on TAR package, which has a test directory with an encrypted tgz file, that gets blocked by some antivirus scanners. Removing it.
    find / -name "cb-never*.tgz" -delete && \
    rm -rf /usr/share/man && \
    rm -rf /tmp/*  && \
    rm -rf /var/cache/apk/* && \
    rm -rf /usr/lib/node_modules/npm/man && \
    rm -rf /usr/lib/node_modules/npm/doc && \
    rm -rf /usr/lib/node_modules/npm/html

- touch $WORKING_DIRECTORY/api/swagger/swagger.json && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger.json
- touch $WORKING_DIRECTORY/api/swagger/swagger.yaml && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger.yaml
- touch $WORKING_DIRECTORY/api/swagger/swagger-remote.json && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger-remote.json
- touch $WORKING_DIRECTORY/api/swagger/swagger-remote.yaml && chmod 666 $WORKING_DIRECTORY/api/swagger/swagger-remote.yaml
- multi-file-swagger multifile.yaml > $WORKING_DIRECTORY/api/swagger/swagger.json
- multi-file-swagger multifile-remote.yaml > $WORKING_DIRECTORY/api/swagger/swagger-remote.json
- sleep 5
- json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml
- json2yaml ./api/swagger/swagger-remote.json > ./api/swagger/swagger-remote.yaml
- swagger validate ./api/swagger/swagger.yaml
script:
  - npm lint