swagger: "2.0"
info:
  version: "0.1.0"
  title: Unfetter Ctf Ingest App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
schemes:
  - http
  - https
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths:
  /upload:
    x-swagger-router-controller: upload
    post:
        operationId: upload
        tags: 
          - "CTF"
        description: > 
          Create a new instance of the model and persist it into the data source.
        produces: 
          - "application/json"
        consumes: 
          - "application/json"
        parameters: 
          - name: "data"
            in: "body"
            required: true
            description: "Model instance data"
            schema: 
              $ref: "#/definitions/UploadRequest"
        responses: 
          "201": 
            description: "Created"
            schema: 
              $ref: "#/definitions/SuccessResponse"
          default: 
            description: "Error"
            schema: 
              $ref: "#/definitions/ErrorResponse"

  /translate/report/url:
    x-swagger-router-controller: translate_report
    post:
      operationId: translate_report_url
      tags: 
        - "CTF"
        - "Translate Report URL"
      description: > 
        Take a report URL translate the URL to that reports JSON equivalent
      produces: 
        - "application/json"
      consumes: 
        - "application/json"
      parameters: 
        - in: "body"
          name: "url"
          description: "Request model"
          schema:
            $ref: "#/definitions/TranslateUrlRequest"
      responses: 
        "201": 
          description: "Created"
          schema: 
            $ref: "#/definitions/TranslateUrlResponse"
        default: 
          description: "Error"
          schema: 
            $ref: "#/definitions/ErrorResponse"

  /translate/report/data:
    x-swagger-router-controller: translate_report
    post:
        operationId: translate_report_data
        tags: 
          - "CTF"
          - "Translate Report JSON Data"
        description: > 
          Take a report JSON data translate the data to a STIX like equivalent, based on mappings confiured in the database
        produces: 
          - "application/json"
        consumes: 
          - "application/json"
        parameters: 
          - name: "data"
            in: "body"
            description: "Request model"
            required: true
            schema: 
              $ref: "#/definitions/TranslateReportData"
        responses:
          "201":
            description: "Created"
            schema: 
              $ref: "#/definitions/TranslateReportDataResponse"
          default: 
            description: "Error"
            schema: 
              $ref: "#/definitions/ErrorResponse"

definitions:
  SuccessResponse:
    type: object
    required:
      - count
    properties:
      count:
        type: number
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  UploadRequest:
    properties:
      data:
        type: string
  TranslateUrlRequest:
    type: object
    properties:
      systemName: 
        type: string
        description: the target url to translate
      url:
        type: string
        description: the target url to translate
    required:
      - url
      - systemName
  TranslateUrlResponse:
    type: object
    required:
      - request
      - translated
    properties:
      request:
        properties:
          systemName:
            type: string
            description: the system this url represents
          url:
            type: string
            description: the target url to translate
      translated:
        properties:
          success:
            type: boolean
            description: true if the url was translated successfully
          url:
            type: string
            description: translated url
  TranslateReportData:
    type: object
    properties:
      systemName:
        type: string
        description: the system this data came from
      payload:
        type: object
        description: the data to translate 
  TranslateReportDataResponse:
    type: object
    required:
      - request
      - translated
    properties:
      request:
        properties:
          systemName:
            type: string
            description: the system this data represents
          payload:
            type: string
            description: the target data to translate
      translated:
        properties:
          success:
            type: boolean
            description: true if the data was translated successfully
          payload:
            type: string
            description: translated data