export enum NotificationRecieveTypes {
    READ_NOTIFICATION = 'READ_NOTIFICATION',
    DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
    READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
    DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS'
}
